INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (1, '华硕 ROG玩家国度', '泰毯Mini 机动战士高达版 鼠标垫+校园系列 小电视 动物橡皮', 'images/img1.png', 96, 1);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (2, ' TUF GAMING X 鬼灭之刃 限定版', '祢豆子 游戏鼠标垫+哔哩哔哩 校园系列 小电视 动物橡皮', 'images/img2.png', 66, 1);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (3, '幻星集Ⅱ 2233 青蛙王子含盖马克杯', '幻星集Ⅱ 2233 青蛙王子含盖马克杯', 'images/img3.png', 99, 1);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (4, '梦幻小电视', '2233 校园系列 便签本*1+哔哩哔哩 校园系列', 'images/img4.png', 1, 2);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (5, '幻星集Ⅱ 2233 漫画笔记本套装B5', '幻星集Ⅱ 2233 漫画笔记本套装B5', 'images/img5.png', 9, 2);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (6, 'BILIBILIGOODS Model系列 跑步梭织夹克', 'BILIBILIGOODS Model系列 跑步梭织夹克', 'images/img10.png', 199, 3);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (7, 'BILIBILI GOODS Model Lv.2系列 复古毛边宽松毛衣', 'BILIBILI GOODS Model Lv.2系列 复古毛边宽松毛衣', 'images/img6.png', 249, 3);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (8, '2233 豆豆眼公式服 午睡抱枕', '哔哩哔哩 2233 豆豆眼公式服 午睡抱枕', 'images/img7.png', 69, 3);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (9, '2233小电视系列 拉边袋A4A5套装', '哔哩哔哩 2233小电视系列 拉边袋A4A5套装', 'images/img8.png', 12, 3);
INSERT INTO pzshop.goods (id, name, info, imgsrc, price, typesId) VALUES (10, '2233 键盘毛绒大礼包', '哔哩哔哩 2233 键盘毛绒大礼包', 'images/img9.png', 666, 2);
